### ISSUE TITLE
how to run the TonKeeper  Web and debugger

### ISSUE THREAD

**Issue by yoga1314** [tonkeeper/tonkeeper-web#10]
I build and success , it is nothing when I click the index

**Comment by KuznetsovNikita** [comment]
Hello @yoga1314 
In case you would like to run web version locally,
please run this commands:

`yarn build:web` - from the root of project, it would build units packages

`cd apps/web` - navigate to web app

`REACT_APP_LOCALES=en yarn start` - run app on localhost
