### ISSUE TITLE
I'm just saying that I'm sorry for myself that I didn't know how to work with this system. I've opened an account here for about two years now, but I don't know how it works. 

### ISSUE THREAD

**Issue by dashali20** [tonkeeper/tonkeeper-web#102]

**Comment by dashali20** [comment]
Oh, sir, what kind of face can I write when I don't know how this system works? I just thank God that he always pays attention to me and does the greatest things for me without any expectations. I am a magnet for attracting money. 🙏💰🎁♾️

**Comment by Sviattoslav** [comment]
Добрый час 7-8 мес назад тоже сдесь зарегистрироваться иногда захожу но так и не знаю зачем я сдесь
