### ISSUE TITLE
Tonkeeper Web & Fragment

### ISSUE THREAD

**Issue by uuonda** [tonkeeper/tonkeeper-web#104]
Hello.

I want to use Tonkeeper Web to interact with Fragment platform. For anything TON related Fragment gives a QR. If I scan it in Tonkeeper Web it just tries to navigate to `tonkeeper://...`  which obviously fails.

How do I push this into `wallet.tonkeeper.com`?

**Comment by KuznetsovNikita** [comment]
Fragment supported Ton Connect 2.0, you may connect to it via extension or desktop
