### ISSUE TITLE
Linux mint - Trace/breakpoint trap - errors for versions >= 3.14.0

### ISSUE THREAD

**Issue by happy-code-com** [tonkeeper/tonkeeper-web#109]
**System:**
Linux mint 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Live CD

**Distrs:** 
Linux amd64 zip

**Checked versions:**

- 🛑 https://github.com/tonkeeper/tonkeeper-web/releases/download/v3.14.3/Tonkeeper-linux-x64-3.14.3.zip
- 🛑 https://github.com/tonkeeper/tonkeeper-web/releases/download/v3.14.2/Tonkeeper-linux-x64-3.14.2.zip
- 🛑 https://github.com/tonkeeper/tonkeeper-web/releases/download/v3.14.0/Tonkeeper-linux-x64-3.14.0.zip
- ✅ https://github.com/tonkeeper/tonkeeper-web/releases/download/v3.13.0/Tonkeeper-linux-x64-3.13.0.zip

**Issue:**

Today I had a problem sending funds through the client version 3.13.0. I have some error on console:

```
21:47:19.060 › Amplitude Logger [Warn]: Event was dropped by a plugin
21:47:57.713 › TypeError: Cannot read properties of null (reading 'split')
    at m (file:///media/mint/usbdrive/Tonkeeper-linux-x64/resources/app.asar/.webpack/renderer/main_window/index.js:4892:35570)
    at async f (file:///media/mint/usbdrive/Tonkeeper-linux-x64/resources/app.asar/.webpack/renderer/main_window/index.js:4892:35103)
    at async Object.mutationFn (file:///media/mint/usbdrive/Tonkeeper-linux-x64/resources/app.asar/.webpack/renderer/main_window/index.js:4722:72966)
```

I tried to update, but any version higher than 3.13.0 gives an error, both on a clean system and a new wallet, and with an old wallet.

```
mint@mint:~$ '/media/mint/usbdrive/Tonkeeper-linux-x64/Tonkeeper'
21:46:29.605 › Application start-up
21:46:29.608 › Reconnect.
6404 Trace/breakpoint trap   (core dumped) '/media/mint/usbdrive/Tonkeeper-linux-x64/Tonkeeper'
```

**Comment by KuznetsovNikita** [comment]
Released fix: https://github.com/tonkeeper/tonkeeper-web/releases/tag/v3.14.6

Thank you for you feedback! @happy-code-com
