### ISSUE TITLE
suggestion for new thing

### ISSUE THREAD

**Issue by muamelAmeer** [tonkeeper/tonkeeper-web#11]
i have suggestion for you to make app like tonkeeper in android , but for linux?
I don't get the best performance in the Firefox Extension

**Comment by KuznetsovNikita** [comment]
Dear @muamelAmeer 
Tonkeeper Desktop for linux coming up in jan (q1 2024)

**Comment by KuznetsovNikita** [comment]
Dear @muamelAmeer 
You may download linux distributives here:
https://github.com/tonkeeper/tonkeeper-web/releases/tag/v3.5.0

It's public beta release
Thank you!
