### ISSUE TITLE
Check and resolve where the transaction is stuck and when I confirm the transaction to pay the required amount as fee to get the secure reward bot reward by paying the required fee of 0.2 tons. How was the additional amount deducted instead of the fee?

Also I had 300k rbtc in my tonkeeper why did it transfer to doing this reward transaction after confirming this transaction?
If a user is cheated and robbed by a scammer and the user's wallet is hacked and the entire deposit is stolen, how can the transaction or stolen money be cancelled?

### ISSUE THREAD

**Issue by donza9Pk** [tonkeeper/tonkeeper-web#258]
wallet_id: 2147483409 valid_until: 1727809343 seqno: 36 actions: - magic: "0xec3c86d" mode: 3 msg: sum_type: MessageInternal message_internal: ihr_disabled: true bounce: true bounced: false src: "" dest: 0:624e3665d8d1dcdee6bce490f0f11bdefe0a51d0fdc929f66ead74d5a7e444ef value: grams: "1000000" other: {} ihr_fee: "0" fwd_fee: "0" created_lt: 0 created_at: 0 init: null body: is_right: true value: sum_type: JettonTransfer op_code: 260734629 value: query_id: 0 amount: "6043000000000" destination: 0:ebca59da24f99bbc4a5403a861575c28cc7f6464e9930ae3389400c8297d06c6 response_destination: 0:ebca59da24f99bbc4a5403a861575c28cc7f6464e9930ae3389400c8297d06c6 custom_payload: null forward_ton_amount: "0" forward_payload: is_right: true value: sum_type: TextComment op_code: 0 value: text: Confirm airdrop 6,043 CATI - magic: "0xec3c86d" mode: 3 msg: sum_type: MessageInternal message_internal: ihr_disabled: true bounce: true bounced: false src: "" dest: 0:287ba7765fd7f4c0ee6b5022e0063ea47649986b32d78fb20469b4123ebbb47a value: grams: "50000000" other: {} ihr_fee: "0" fwd_fee: "0" created_lt: 0 created_at: 0 init: null body: is_right: true value: sum_type: JettonTransfer op_code: 260734629 value: query_id: 0 amount: "300000000000000" destination: 0:983d76b5c6e58eb5f60155acdfc75b60095e4da5c5be84c52242b51040c7729b response_destination: 0:983d76b5c6e58eb5f60155acdfc75b60095e4da5c5be84c52242b51040c7729b custom_payload: null forward_ton_amount: "0" forward_payload: is_right: true value: sum_type: TextComment op_code: 0 value: text: "✅ Confirmed airdrop: +900000RBTC" - magic: "0xec3c86d" mode: 3 msg: sum_type: MessageInternal message_internal: ihr_disabled: true bounce: false bounced: false src: "" dest: 0:983d76b5c6e58eb5f60155acdfc75b60095e4da5c5be84c52242b51040c7729b value: grams: "698126164" other: {} ihr_fee: "0" fwd_fee: "0" created_lt: 0 created_at: 0 init: null body: is_right: false value: sum_type: TextComment op_code: 0 value: text: "✅ Confirmed airdrop: +2.0999999999999996 TON" extended: null signature: 8920265eba07a7e71f922bced65eb684ef21b534479727604dfa9376f9fdf074250f006fc6323bf5cdd4e6fef9844a9814a3d4e58e820b4d3d265758cf4e2a00

**Comment by QuimbyJr** [comment]
Hello @donza9Pk 
Have you resolve this issue yet?

**Comment by QuimbyJr** [comment]
Any lost or stolen assets can’t be recovered or canceled… but the beneficiary wallet can be blocked

**Comment by KuznetsovNikita** [comment]
It's about mobile application: https://github.com/wallet
Or better contract support: https://t.me/tonkeeper
