### ISSUE TITLE
Wallet goes blank after clicking icon severally to switch network

### ISSUE THREAD

**Issue by marcus1666** [tonkeeper/tonkeeper-web#320]
I noticed since [v3.26.1](https://github.com/tonkeeper/tonkeeper-web/releases/tag/v3.26.1)
issues is also present at [Tonkeeper v3.26.0](https://github.com/tonkeeper/tonkeeper-web/releases/tag/v3.26.0)

This test was carried out on the chrome extension

Here is the blank screen presented with after trying to switch network
![image](https://github.com/user-attachments/assets/51ab3e9e-b0c8-4511-9c42-dbd308ff3362)

**Comment by sohAppAsia** [comment]
me22222222, Please fix it asap, my mom is waiting for me withdraw the money for recovery.....

**Comment by salateur** [comment]
Hello! You do not need to switch networks anymore via the dev menu with the new versions. If you need to switch from Testnet to Mainnet you have two ways.

1. Just add your testnet wallet via the main screen. Press on Account > Manage > Set up a new wallet.  
2. The same works with the mainnet wallet, you add it simply via "Manage" > Set up a new wallet. 

If you are not sure about the seed-phrase you need to use - just check the testnet seed-phrase in the settings > backup and use it for your mainnet network account. 

Also, it's worth mentioning that testnet assets are for testing purposes only, you can't send testnet assets to mainnet and vice versa. 
If you find any other questions or troubles - lemme know. Have a good day!

**Comment by marcus1666** [comment]
Thanks for the clarification

**Comment by posuihushui** [comment]
If this switch page contains this declaration, there will be no issues.
