### ISSUE TITLE
tc://?v=2&id=cbb15e919d20b41f48de16ee105950409faef50d7fa11b0f48decfb8ceeeb06e&r=%7B%22manifestUrl%22%3A%22https%3A%2F%2Fdyor.io%2Ftonconnect-manifest.json%22%2C%22items%22%3A%5B%7B%22name%22%3A%22ton_addr%22%7D%2C%7B%22name%22%3A%22ton_proof%22%2C%22payload%22%3A%22adab8ddce061e5da0000000067607ef08f8b3ed0ab4b397722eb085b4a0bfe18%22%7D%5D%7D

### ISSUE THREAD

**Issue by amirmmwiz** [tonkeeper/tonkeeper-web#336]

**Comment by tuuputamadre** [comment]
tc://?v=2&id=537fab89bb7e3ed6416f40a1d8e271015095f961397c960c614425b1d863e45c&r=%7B%22manifestUrl%22%3A%22https%3A%2F%2Fgetgems.io%2Ftcm.json%22%2C%22items%22%3A%5B%7B%22name%22%3A%22ton_addr%22%7D%2C%7B%22name%22%3A%22ton_proof%22%2C%22payload%22%3A%22gems%22%7D%5D%7D&ret=none

**Comment by Ascalad** [comment]
Pull request I encountered a problem with my Tonkeeper and Tonkeeper Pro wallets, which is that funds are not being received in my account. This request is being created to resolve these problems.

**Comment by csu64300-blip** [comment]
``

**Comment by csu64300-blip** [comment]
> ``

**Comment by csu64300-blip** [comment]
@

**Comment by makavelico931-afk** [comment]
@
